config/urls.py
from django.contrib import admin
from django.urls import path,include
from booker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('booker/',include('booker.urls')),
    path('', views.index,name='index'),
    path('common/',include('common.urls')),
    path('pybo/',include('pybo.urls'))
]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path
from . import views

app_name='pybo'

urlpatterns = [
    path('', views.index,name='index'),
    path('list/',views.ProfileViewList.as_view(),name='profile-list'),
    path('profile/create/',views.profile_create,name='profile-create'),
    path('profile/detail/<int:profile_id>',views.profile_detail,name='detail'),
    path('profile/like/<int:profile_id>',views.profile_like,name='like'),
    path('profile/unlike/<int:profile_id>',views.profile_unlike,name='unlike'),
    path('profile/comment/delete/<int:comment_id>',views.comment_delete,name='comment-delete'),
    path('profile/comment/update/<int:profile_id>/<int:comment_id>',views.comment_update,name='comment-update'),
    path('profile/profile/delete/<int:profile_id>',views.delete_profile,name='profile-delete'),
    path('profile/profile/update/<int:profile_id>',views.update_profile,name='profile-update'),
    path('hello/<int:user_id>',views.UserProfileView.as_view(),name='profile')


]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    create_at = models.DateTimeField()
    like = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return self.title


class ProfileComment(models.Model):
    author = models.CharField(max_length=100)
    content = models.CharField(max_length=200)
    like = models.ManyToManyField(User, blank=True)
    create_at = models.DateTimeField()
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    def __str__(self):
        return self.title

pybo/forms.py
from django import forms
from .models import Profile,ProfileComment

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['title','content']


class ProfileCommentForm(forms.ModelForm):
    class Meta:
        model = ProfileComment
        fields = ['content']

pybo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Profile,ProfileComment
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm,ProfileCommentForm
from django.utils import timezone


def index(request):
    return render(request, 'pybo/pybo.html', {})


class ProfileViewList(ListView):
    model = Profile
    template_name = 'profile_list.html'
    context_object_name = 'profiles'
    ordering = ['-create_at']
    paginate_by = 10


@login_required(login_url='login')
def profile_create(request):
    if request.method =="POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.author = request.user
            profile.create_at = timezone.now()
            profile.save()
            return redirect('pybo:profile-list')
    else:
        form=ProfileForm()
    context = {'form':form}
    return render(request,'pybo/profile-create.html',context)

def profile_detail(request,profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)
    # comment = Comment.objects.filter(post=book).order_by(['-create_at'])
    if request.method == "POST":
        if request.user.is_authenticated:
            form = ProfileCommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = request.user
                comment.create_at = timezone.now()
                comment.profile = profile
                comment.save()
                return redirect('pybo:detail', profile_id)
        else:
            return redirect('login')
    else:
        form = ProfileCommentForm()
        liked = False
        if request.user in profile.like.all():
            liked = True
    context = {'profile':profile,'form':form,'liked':liked}
    return render(request, 'pybo/detail.html', context)


@login_required(login_url='login')
def delete_profile(request,profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)
    if request.user.username == profile.author:
        profile.delete()
    return redirect('pybo:profile-list')

@login_required(login_url='login')
def update_profile(request,profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)
    if request.method == 'POST':
        if request.user.username == profile.author:
            form = ProfileForm(request.POST,instance=profile)
            if form.is_valid:
                profile = form.save()
            return redirect('pybo:detail',profile_id)
    else:
        form=ProfileForm()
    context = {'profile': profile,'form': form}
    return render(request, 'pybo/profile-update.html', context)



@login_required(login_url='login')
def profile_like(request, profile_id):
    """
    책 추천하기 버튼 누르기
    """
    profile = get_object_or_404(Profile, pk=profile_id)
    profile.like.add(request.user)
    profile.save()
    return redirect('pybo:detail',profile_id)

@login_required(login_url='login')
def profile_unlike(request, profile_id):
    """
    책 추천 풀기
    """
    book = get_object_or_404(Profile, pk=profile_id)
    book.like.remove(request.user)
    book.save()
    return redirect('pybo:detail',profile_id)

def comment_delete(request, comment_id):
    """
    댓글 삭제
    """
    comment = get_object_or_404(ProfileComment, pk=comment_id)
    profile = comment.profile
    if request.user.username == comment.author:
        comment.delete()
    return redirect('pybo:detail',profile.id)

@login_required(login_url='login')
def comment_update(request, profile_id,comment_id):
    """
    댓글 수정하기
    """
    comment = get_object_or_404(ProfileComment, pk=comment_id)
    profile = get_object_or_404(Profile, pk=profile_id)
    if request.method =="POST":
        form = ProfileCommentForm(request.POST,instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect('pybo:detail',profile_id)
    else:
        form = ProfileCommentForm()
    liked = False
    if request.user in profile.like.all():
        liked = True
    context = {'profile': profile, 'form': form, 'liked': liked}
    return render(request, 'pybo/comment-update.html', context)


class UserProfileView(ListView):
    model = Profile
    template_name = 'pybo/hello.html'
    context_object_name = 'profiles'
    paginate_by = 10
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=self.request.user).order_by('-create_at')

templates/pybo/comment-update.html
{% extends 'pybo-base.html' %}
{% block content %}
<section class="section-pybo">
 <div class="detail-all">
                <!-- left -->
                <div class="detail-left">
                    <div class="comment-form">
                    <h2>댓글</h2>
                    <div class="detail-comment">
                        <form method="post">
                            {% csrf_token %}
                            <label for="content" class="comment-label">댓글</label>
                            <input type="text" name="content" id="content" placeholder="수정할 댓글을 입력해주세요" required>
                            <button type="submit" class="book-btn">댓글 수정하기</button>
                        </form>
                    </div>
                    </div>
                <br>
                    {% for comment in profile.profilecomment_set.all %}
                <div class="comment-list">
                    <div class="comment">
                        <div class="comment-update">
                            <p><b>{{ comment.author }}</b></p>
                        </div>
                    </div>
                    <p>{{ comment.content }}</p>
                </div>
                    {% endfor %}
                </div>
                <!-- left -->
                <!-- right -->
                <div class="detail-right">
                    <h2>{{ profile.title }}</h2>
                    <div class="detail-info">
                    <div class="detail-img">
                        <img src="{{ book.cover }}" style="height: 150px;">
                    </div>
                        <table class="detail-table">
                            <tbody>
                                <tr>
                                    <td>작성자</td>
                                    <td>{{ profile.author }}</td>
                                </tr>
                                <tr>
                                    <td>작성일</td>
                                    <td>{{ profile.create_at }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="detail-description">
                        <p><b>내용</b></p><br>
                        {{ profile.content }}
                    </div>
                    <div style="width: 90%;">
                        {% if liked %}
                        <a href="{% url 'pybo:unlike' profile.id %}" class="book-btn">이미 추천하셨습니다</a>
                        {% else %}
                    <a href="{% url 'pybo:like' profile.id %}" class="book-btn">추천하기</a>
                        {% endif %}
                </div>
            </div>
            <!-- right -->
            </div>
            <!-- right -->
            </div>
</section>
{% endblock %}

templates/pybo/detail.html
{% extends 'pybo-base.html' %}
{% block content %}
<section class="section-pybo">
 <div class="detail-all">
                <!-- left -->
                <div class="detail-left">
                    <div class="comment-form">
                    <h2>댓글</h2>
                    <div class="detail-comment">
                        <form method="post">
                            {% csrf_token %}
                            <label for="content" class="comment-label">댓글</label>
                            <input type="text" name="content" id="content" placeholder="댓글을 입력해주세요" required>
                            <button type="submit" class="book-btn">댓글추가하기</button>
                        </form>
                    </div>
                    </div>
                <br>
                    {% for comment in profile.profilecomment_set.all %}
                <div class="comment-list">
                    <div class="comment">
                        <div class="comment-update">
                            <p class="{{ comment.id }}"><b>{{ comment.author }}</b></p>
                            {% if user.username == comment.author %}
                            <a href="{% url 'pybo:comment-update' profile.id comment.id %}" class="comment-text {{comment.id}}"><i class='bx bxs-message-square-edit'></i></a>
                            <a class="comment-text {{comment.id}}"
                            onclick="deleteModal('{{comment.id}}')"><i class='bx bxs-message-square-x' ></i></a>
                            <div class="comment-confirm" id="{{ comment.id }}" style="display:none;">
                                <p><b>정말로 삭제하시겠습니까?</b></p>
                                <a  class="comment-delete" href="{% url 'pybo:comment-delete' comment.id %}">삭제하기</a>
                                <a onclick="unDeleteModal('{{comment.id}}')" class="comment-delete">취소하기</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <p class="{{comment.id}}">{{ comment.content }}</p>
                </div>
                    {% endfor %}
                </div>
                <!-- left -->
                <!-- right -->
                <div class="detail-right">
                    <h2>{{ profile.title }}</h2>
                    <div class="detail-info">
                    <div class="detail-img">
                        <img src="{{ book.cover }}" style="height: 150px;">
                    </div>
                        <table class="detail-table">
                            <tbody>
                                <tr>
                                    <td>작성자</td>
                                    <td>{{ profile.author }}</td>
                                </tr>
                                <tr>
                                    <td>작성일</td>
                                    <td>{{ profile.create_at }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="detail-description">
                        <p><b>내용</b></p><br>
                        {{ profile.content }}
                    </div>
                    <div style="width: 90%;">
                        {% if liked %}
                        <a href="{% url 'pybo:unlike' profile.id %}" class="book-btn">이미 추천하셨습니다</a>
                        {% else %}
                    <a href="{% url 'pybo:like' profile.id %}" class="book-btn">추천하기</a>
                        {% endif %}
                        {% if user.username == profile.author %}
                        <a href="{% url 'pybo:profile-update' profile.id%}" class="book-btn">글 수정하기</a>
                        <button class="book-btn" onclick="DeleteProfile()" id="profile-delete" style="font-size:16px;">게시글 삭제하기</button>
                        <a href="{% url 'pybo:profile-delete' profile.id %}" id="profile-confirm"
                           class="book-btn" style="display:none;;">정말로 삭제하시겠습니까?</a>
                        {% endif %}
                </div>
            </div>
            <!-- right -->
            </div>
    <script>
        function deleteModal(n) {
            var cc = document.getElementsByClassName(n);
            var ci = document.getElementById(n);
            for (var i = 0; i < cc.length; i++) {
                cc[i].style.display = "none";
            }
                ci.style.display = "block";
            }
        function unDeleteModal(n) {
            var cc = document.getElementsByClassName(n);
            var ci = document.getElementById(n);
            for (var i = 0; i < cc.length; i++) {
                cc[i].style.display = "block";
            }
                ci.style.display = "none";
            }
        function DeleteProfile(){
            var btn1 = document.getElementById('profile-delete');
            var btn2 = document.getElementById('profile-confirm');
            btn1.style.display = "none";
            btn2.style.display = "flex";
            }
        </script>
</section>
{% endblock %}

templates/pybo/hello.html
{% extends 'pybo-base.html' %}
{% block content %}
<section class="section-pybo">
            <div class="booker-list">
                <h2>{{ user.username }}</h2>
                <p>{{ user.username }}의 자기소개</p>
                 <table class="booker-table">
                    <thead>
                        <tr>
                            <th>소개</th>
                            <th>작성자</th>
                            <th>댓글수</th>
                            <th>작성일</th>
                        </tr>
                    </thead>
                    <tbody class="book-tbody">
                    {% for profile in profiles %}
                        <tr>
                            <td><a href="{% url 'pybo:detail' profile.id %}" class="book-page">{{ profile.title }}</a></td>
                            <td>{{ profile.author }}</td>
                            <td>{{ profile.profilecomment_set.count }}</td>
                            <td>{{ profile.create_at }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <nav aria-label="Page navigation profile">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a></li>
        {% endif %}
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item active"><span class="page-link">{{ page_num }}</span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a></li>
        {% endif %}
      </ul>
    </nav>

                </div>

  </section>
  {% endblock %}

templates/pybo/profile-create.html
{% extends 'pybo-base.html' %}
{% block content %}
<section class="section-pybo">
            <div class="booker-list" style="display:flex; justify-content:center">
                <h2>나를 소개합니다</h2>
               <div class="create-profile">
                <form method="POST" enctype="multipart/form-data" class="profile-create">
                    {% csrf_token %}
                    <input type="text" name="title" id="title" class="profile-text" placeholder="내소개제목은?" required>
                    <textarea name="content" id="content" class="profile-textarea" placeholder="나를 소개해보세요!" required></textarea>
                    <button type="submit" class="book-btn" style="margin-top: 30px ;">게시물 작성</button>
                  </form>
               </div>
            </div>
        </section>
{% endblock %}

templates/pybo/profile-update.html
{% extends 'pybo-base.html' %}
{% block content %}
<section class="section-pybo">
            <div class="booker-list" style="display:flex; justify-content:center">
                <h2>프로필 수정하기</h2>
               <div class="create-profile">
                <form method="POST" enctype="multipart/form-data" class="profile-create">
                    {% csrf_token %}
                    <input type="text" name="title" id="title" class="profile-text" placeholder="내소개제목은?" value="{{ profile.title }}">
                    <textarea name="content" id="content" class="profile-textarea" placeholder="나를 소개해보세요!" >{{ profile.content }}</textarea>
                    <button type="submit" class="book-btn" style="margin-top: 30px ;">게시물 수정</button>
                  </form>
               </div>
            </div>
        </section>
{% endblock %}

templates/pybo/profile_list.html
{% extends 'pybo-base.html' %}
{% block content %}
<section class="section-pybo">
            <div class="booker-list">
                <h2>프로필 목록</h2>
                <table class="booker-table">
                    <thead>
                        <tr>
                            <th>소개</th>
                            <th>작성자</th>
                            <th>댓글수</th>
                            <th>작성일</th>
                        </tr>
                    </thead>
                    <tbody class="book-tbody">
                    {% for profile in profiles %}
                        <tr>
                            <td><a href="{% url 'pybo:detail' profile.id %}" class="book-page">{{ profile.title }}</a></td>
                            <td>{{ profile.author }}</td>
                            <td>{{ profile.profilecomment_set.count }}</td>
                            <td>{{ profile.create_at }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <nav aria-label="Page navigation profile">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a></li>
        {% endif %}
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item active"><span class="page-link">{{ page_num }}</span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a></li>
        {% endif %}
      </ul>
    </nav>
                </div>


        </section>
{% endblock %}

templates/pybo/pybo.html
{% extends 'pybo-base.html' %}
{% block content %}
<section class="section-pybo">
            <div class="home-content">
                <h1>안녕하세요!</h1>
                <h3>자기를 소개해보세요!</h3>
                <p>Pybo는 당신에게 많은 사람을
                </p>
                <p>소개시켜줄것입니다!</p>
                <a href="{% url 'pybo:profile-list' %}" class="book-btn">사람들 프로필 보러가기</a>
                <a href="{% url 'pybo:profile-create' %}" class="book-btn" style="margin-top:20px">새 프로필 작성하기</a>
            </div>
        </section>
{% endblock %}