booker/urls.py
from django.urls import path, include
from . import views

app_name='booker'

urlpatterns = [
    path('list', views.book_list, name='book-list'),
    path('detail/<int:book_id>/', views.book_detail, name='detail'),
    path('detail/like/<int:book_id>/', views.book_like, name='like'),
    path('detail/unlike/<int:book_id>/',views.book_unlike,name='unlike'),
    path('random/', views.book_reference, name='random'),
    path('profile/',views.book_profile, name='profile'),
    path('comment/delete/<int:comment_id>',views.comment_delete,name='comment-delete'),
    path('comment/update/<int:book_id>/<int:comment_id>', views.comment_update, name="comment-update"),
    path('about/us/',views.about_us,name="about-us")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from booker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('booker/',include('booker.urls')),
    path('', views.index,name='index'),
    path('common/',include('common.urls')),
    path('pybo/',include('pybo.urls'))
]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path
from . import views

app_name='pybo'

urlpatterns = [
    path('', views.index,name='index'),
    path('list/',views.ProfileViewList.as_view(),name='profile-list'),
    path('profile/create/',views.profile_create,name='profile-create'),
    path('profile/detail/<int:profile_id>',views.profile_detail,name='detail'),
    path('profile/like/<int:profile_id>',views.profile_like,name='like'),
    path('profile/unlike/<int:profile_id>',views.profile_unlike,name='unlike'),
    path('profile/comment/delete/<int:comment_id>',views.comment_delete,name='comment-delete'),
    path('profile/comment/update/<int:profile_id>/<int:comment_id>',views.comment_update,name='comment-update'),
    path('profile/profile/delete/<int:profile_id>',views.delete_profile,name='profile-delete'),
    path('profile/profile/update/<int:profile_id>',views.update_profile,name='profile-update'),
    path('hello/<int:user_id>',views.UserProfileView.as_view(),name='profile')


]

booker/models.py
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
    title = models.CharField('제목',max_length=50,unique=True,null=False)
    extent=models.CharField('출판사',max_length=50)
    description=models.TextField('소개',max_length=500)
    charge = models.CharField('가격',max_length=10)
    cover = models.CharField('책표지',max_length=100)
    rights = models.CharField('저자',max_length=50)
    issued_at = models.CharField('출판일자',max_length=20)
    like = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return self.title



class Comment(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.CharField('내용',max_length=255)
    post = models.ForeignKey(Book,on_delete=models.CASCADE)
    create_at = models.DateTimeField()
    def __str__(self):
        return self.content
    class Meta:
        ordering = ['-create_at']

booker/forms.py
from django import forms
from booker.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content':'댓글내용'
        }

booker/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Book,Comment
from django.core.paginator import Paginator
from .forms import CommentForm
from django.utils import timezone
import random
from django.db.models import Count
from django.contrib.auth.decorators import login_required

def index(request):
    """
    홈으로 가기
    """
    return render(request,'booker/home.html',{})

# class BookListView(ListView):
#     model = Book
#     template_name = 'booker/booklist.html'
#     context_object_name = 'booklist'
#     paginate_by = 10
#     ordering = ['-issued_at']
#     page_kwarg = 'page'

def book_list(request):
    page = request.GET.get('page','1')
    ca = request.GET.get('ca','recent')
    if ca == 'title':
        book_list = Book.objects.order_by('title')
    elif ca == 'liked':
        book_list = Book.objects.order_by('-issued_at')
        book_list = book_list.annotate(
            num_like=Count('like')).order_by('-num_like','-issued_at')
    elif ca == 'comment':
        book_list = Book.objects.order_by('-issued_at')
        book_list = book_list.annotate(
            num_comment=Count('comment')).order_by('-num_comment','-issued_at')
    else:
        book_list = Book.objects.order_by('-issued_at')

    paginator = Paginator(book_list,10)
    page_obj = paginator.get_page(page)
    context = {'booklist':page_obj,'page':page}
    return render(request,'booker/booklist.html',context)

def book_detail(request,book_id):
    book = get_object_or_404(Book, pk=book_id)
    # comment = Comment.objects.filter(post=book).order_by(['-create_at'])
    if request.method == "POST":
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = request.user
                comment.create_at = timezone.now()
                comment.post = book
                comment.save()
                return redirect('booker:detail', book_id)
        else:
            return redirect('login')
    else:
        form = CommentForm()
        liked = False
        if request.user in book.like.all():
            liked = True
    context = {'book':book,'form':form,'liked':liked}
    return render(request, 'booker/book-detail.html', context)

@login_required(login_url='login')
def book_like(request, book_id):
    """
    책 추천하기 버튼 누르기
    """
    book = get_object_or_404(Book, pk=book_id)
    book.like.add(request.user)
    book.save()
    return redirect('booker:detail',book_id)


@login_required(login_url='login')
def book_unlike(request, book_id):
    """
    책 추천 풀기
    """
    book = get_object_or_404(Book, pk=book_id)
    book.like.remove(request.user)
    book.save()
    return redirect('booker:detail',book_id)




def book_reference(request):
    """
    랜덤 책 뽑기
    """
    book_id = random.randrange(1, 819)
    if request.method == 'POST':
        if request.user.is_authenticated:
            return redirect('booker:detail', book_id)
        else:
            return redirect('login')
    return render(request, 'booker/book-random.html')


def book_profile(request):
    """
    프로필 리스트 불러오기
    """
    sa = request.GET.get('sa','liked')
    page = request.GET.get('page','1')
    user = request.user
    if sa == 'comment':
        comments = Comment.objects.filter(author=request.user)
        book_list = [comment.post for comment in comments]
        book_title_set = set()
        books = []
        for book in book_list:
            if book.title not in book_title_set:
                book_title_set.add(book.title)
                books.append(book)
    else:
        books = Book.objects.filter(like=user)
    paginator = Paginator(books,7)
    page_obj = paginator.get_page(page)
    context = {'books': page_obj}
    return render(request, 'booker/profile.html', context)


@login_required(login_url='login')
def comment_delete(request, comment_id):
    """
    댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    post = comment.post
    if request.user == comment.author:
        comment.delete()
    return redirect('booker:detail',post.id)

@login_required(login_url='login')
def comment_update(request, book_id,comment_id):
    """
    댓글 수정하기
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    book = get_object_or_404(Book, pk=book_id)
    if request.method =="POST":
        form = CommentForm(request.POST,instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect('booker:detail',book_id)
    else:
        form = CommentForm()
    liked = False
    if request.user in book.like.all():
        liked = True
    context = {'book': book, 'form': form, 'liked': liked}
    return render(request, 'booker/book-update.html', context)


def about_us(request):
    return render(request ,'booker/aboutus.html', {})

templates/booker/aboutus.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="section-home">
            <div class="booker-list">
               <div class="about-us">
                   <h2>Marmin</h2>
                   <h3>안녕하세요! 뭐든 만들고싶은 개발자 박태욱입니다</h3>
                   <h2>언어</h2>
                   <p>제가 공부한 언어는</p>
                   <p><strong>JAVA</strong></p>
                   <p><strong>Python</strong></p>
                   <p><strong>HTML,CSS,JS</strong></p>
                   <p><strong>C</strong></p>
                   <p><strong>SQL</strong></p>
                   <br>
                   <h2>공부한것들</h2>
                   <p>공부한 프레임워크 라이브러리 DB 등등</p>
                   <p><strong>SpringBoot</strong></p>
                   <p><strong>Django</strong></p>
                   <p><strong>React.js</strong></p>
                   <p><strong>Docker</strong></p>
                   <p><strong>VanillaJs</strong></p>
                   <p><strong>MySQL</strong></p>
               </div>
               <div style="display: flex;">
            <a href="https://github.com/marmin-dev" style="margin:30px;"><img src="{% static 'css/img/github.png' %}" class="about-logo"></a>
            <br>
            <a href="https://marmindev.notion.site/IT-1ccb391d78844eddaeae38eb717613e2" style="margin:30px ;"><img src="{% static 'css/img/notion.png' %}" class="about-logo"></a>
               </div>
            </div>
        </section>

{% endblock %}

templates/booker/book-detail.html
{% extends 'base.html' %}
{% block content %}
<section class="section-home">
 <div class="detail-all">
                <!-- left -->
                <div class="detail-left">
                    <div class="comment-form">
                    <h2>댓글</h2>
                    <div class="detail-comment">
                        <form method="post">
                            {% csrf_token %}
                            <label for="content" class="comment-label">댓글</label>
                            <input type="text" name="content" id="content" placeholder="댓글을 입력해주세요" required>
                            <button type="submit" class="book-btn">댓글추가하기</button>
                        </form>
                    </div>
                    </div>
                <br>
                    {% for comment in book.comment_set.all %}
                <div class="comment-list">
                    <div class="comment">
                        <div class="comment-update">
                            <p class="{{ comment.id }}"><b>{{ comment.author }}</b></p>
                            {% if user == comment.author %}
                            <a href="{% url 'booker:comment-update' book.id comment.id %}" class="comment-text {{comment.id}}"><i class='bx bxs-message-square-edit'></i></a>
                            <a class="comment-text {{comment.id}}"
                            onclick="deleteModal('{{comment.id}}')"><i class='bx bxs-message-square-x' ></i></a>
                            <div class="comment-confirm" id="{{ comment.id }}" style="display:none;">
                                <p><b>정말로 삭제하시겠습니까?</b></p>
                                <a  class="comment-delete" href="{% url 'booker:comment-delete' comment.id %}">삭제하기</a>
                                <a onclick="unDeleteModal('{{comment.id}}')" class="comment-delete">취소하기</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <p class="{{comment.id}}">{{ comment.content }}</p>
                </div>
                    {% endfor %}
                </div>
                <!-- left -->
                <!-- right -->
                <div class="detail-right">
                    <h2>{{ book.title }}</h2>
                    <div class="detail-info">
                    <div class="detail-img">
                        <img src="{{ book.cover }}" style="height: 150px;">
                    </div>
                        <table class="detail-table">
                            <tbody>
                                <tr>
                                    <td>출판사</td>
                                    <td>{{ book.extent }}</td>
                                </tr>
                                <tr>
                                    <td>저자</td>
                                    <td>{{ book.rights }}</td>
                                </tr>
                                <tr>
                                    <td>가격</td>
                                    <td>{{ book.charge }}</td>
                                </tr>
                                <tr>
                                    <td>출간일</td>
                                    <td>{{ book.issued_at }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="detail-description">
                        <p><b>요약</b></p><br>
                        {{ book.description }}
                    </div>
                    <div style="width: 90%;">
                        {% if liked %}
                        <a href="{% url 'booker:unlike' book.id %}" class="book-btn">이미 추천하셨습니다</a>
                        {% else %}
                    <a href="{% url 'booker:like' book.id %}" class="book-btn">추천하기</a>
                        {% endif %}
                </div>
            </div>
            <!-- right -->
            </div>
    <script>
        function deleteModal(n) {
            var cc = document.getElementsByClassName(n);
            var ci = document.getElementById(n);
            for (var i = 0; i < cc.length; i++) {
                cc[i].style.display = "none";
            }
                ci.style.display = "flex";
            }
        function unDeleteModal(n) {
            var cc = document.getElementsByClassName(n);
            var ci = document.getElementById(n);
            for (var i = 0; i < cc.length; i++) {
                cc[i].style.display = "block";
            }
                ci.style.display = "flex";
            }
        </script>
</section>
{% endblock %}

templates/booker/book-random.html
{% extends 'base.html' %}
{% block content %}
<section class="section-home">
            <div class="home-content">
                <h1>랜덤 책 뽑기</h1>
                <h3>랜덤으로 책을 추천해드려요!</h3>
                <h3>아래 버튼을 눌러보세요!</h3>
                <form method="post" action="{% url 'booker:random' %}">
                    {% csrf_token %}
                  <button type="submit" class="book-btn">랜덤 책 뽑기</button>
                </form>
            </div>
        </section>
{% endblock %}

templates/booker/book-update.html
{% extends 'base.html' %}
{% block content %}
<section class="section-home">
 <div class="detail-all">
                <!-- left -->
                <div class="detail-left">
                    <div class="comment-form">
                    <h2>댓글</h2>
                    <div class="detail-comment">
                        <form method="post">
                            {% csrf_token %}
                            <label for="content" class="comment-label">댓글</label>
                            <input type="text" name="content" id="content" placeholder="수정할 댓글을 입력해주세요" required>
                            <button type="submit" class="book-btn">댓글 수정하기</button>
                        </form>
                    </div>
                    </div>
                <br>
                    {% for comment in book.comment_set.all %}
                <div class="comment-list">
                    <div class="comment">
                        <div class="comment-update">
                            <p><b>{{ comment.author }}</b></p>
                        </div>
                    </div>
                    <p>{{ comment.content }}</p>
                </div>
                    {% endfor %}
                </div>
                <!-- left -->
                <!-- right -->
                <div class="detail-right">
                    <h2>{{ book.title }}</h2>
                    <div class="detail-info">
                    <div class="detail-img">
                        <img src="{{ book.cover }}" style="height: 150px;">
                    </div>
                        <table class="detail-table">
                            <tbody>
                                <tr>
                                    <td>출판사</td>
                                    <td>{{ book.extent }}</td>
                                </tr>
                                <tr>
                                    <td>저자</td>
                                    <td>{{ book.rights }}</td>
                                </tr>
                                <tr>
                                    <td>가격</td>
                                    <td>{{ book.charge }}</td>
                                </tr>
                                <tr>
                                    <td>출간일</td>
                                    <td>{{ book.issued_at }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="detail-description">
                        <p><b>요약</b></p><br>
                        {{ book.description }}
                    </div>
                    <div style="width: 90%;">
                        {% if liked %}
                        <a class="book-btn">이미 추천하셨습니다</a>
                        {% else %}
                    <a href="{% url 'booker:like' book.id %}" class="book-btn">추천하기</a>
                        {% endif %}
                </div>
            </div>
            <!-- right -->
            </div>
</section>
{% endblock %}

templates/booker/booklist.html
{% extends 'base.html' %}
{% block content %}
<section class="section-home">
            <div class="booker-list">
                <h2>책 목록</h2>
                <select class="book-select" id="ac">
                    <option value="recent" id="ca-recent">최근</option>
                    <option value="title" id="ca-title">제목순</option>
                    <option value="liked" id="ca-liked">추천순</option>
                    <option value="comment" id="ca-comment">댓글순</option>
                </select>
                <table class="booker-table">
                    <thead>
                        <tr>
                            <th>책표지</th>
                            <th>책제목</th>
                            <th>댓글수/추천수</th>
                            <th>책저자</th>
                            <th>출간일</th>
                        </tr>
                    </thead>
                    <tbody class="book-tbody">
                    {% for book in booklist %}
                        <tr>
                            <td><img src="{{ book.cover }}" class="list-img"></td>
                            <td><a href="{% url 'booker:detail' book.id %}" class="book-page">{{ book.title }}</a></td>
                            <td>{{ book.comment_set.count }}/{{ book.like.all.count }}</td>
                            <td>{{ book.rights }}</td>
                            <td>{{ book.issued_at }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="book-paginate">
                      {% for page_number in booklist.paginator.page_range %}
  {% if page_number >= booklist.number|add:-5 and page_number <= booklist.number|add:5 %}
    {% if page_number == booklist.number %}
        <li class="bookpg-li" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}"
                   href="#">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="bookpg-li">
            <a class="page-link" href="#" data-page="{{ page_number }}">
                {{ page_number }}
            </a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
                </div>
            </div>

        </section>
        <form id="searchForm" method="get" action="{{ request.path }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
            <input type="hidden" id="ca" name="ca" value="{{ ca }}">
        </form>
<script>
const url = new URL(window.location.href);
const urlParams = url.searchParams;
const valCa = urlParams.get('ca');

if (valCa == "title") {
  let title = document.getElementById("ca-title");
  title.setAttribute("selected", true);
} else if (valCa == "liked") {
  let liked = document.getElementById("ca-liked");
  liked.setAttribute("selected", true);
} else if (valCa == "comment") {
  let comment = document.getElementById("ca-comment");
  comment.setAttribute("selected", true);
} else {
    let recent = document.getElementById("ca-recent")
    recent.setAttribute("selected", true);
}

const ca = document.getElementById('ca')
ca.value = valCa
</script>
        {% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $(".page-link").on('click',function(){
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });
         $("#ac").on('change',function(){
            $("#ca").val($(this).val());
            $("#page").val(1);
            $("#searchForm").submit();
        });
        });
    </script>
        {% endblock %}
{% endblock %}

templates/booker/home.html
{% extends 'base.html' %}
{% block content %}
<section class="section-home">
            <div class="home-content">
                <h1>안녕하세요!</h1>
                <h3>오늘 무엇을 읽을까요?</h3>
                <p>booker는 국가에서 제공하는 데이터베이스 기반으로
                </p>
                <p>사용자에게 책을 추천해드립니다.</p>
                <a href="{% url 'booker:book-list' %}" class="book-btn">책 목록 불러오기</a>
            </div>
        </section>
{% endblock %}

templates/booker/profile.html
{% extends 'base.html' %}
{% block content %}
<section class="section-home">
            <div class="booker-list">
                <h2>{{ user.username }}</h2>
                <p>안녕하세요! {{ user.username }}님!</p>
                <div class="profile-ca">
                    <form id="likeForm" method="get" action="{{ request.path }}">
                        <p class="profile-sel" id="cl1">내가 추천한 책</p>
                        <input type="hidden" name="sa" id="sa1" value="like">
                    </form>
                    <form id="commentForm" method="get" action="{{ request.path }}">
                    <p class="profile-sel" id="cl2">내가 댓글단 책</p>
                    <input type="hidden" name="sa" id="sa2" value="comment">
                    </form>
                </div>
                <table class="booker-table">
                    <thead>
                        <tr>
                            <th>책표지</th>
                            <th>책제목</th>
                            <th>댓글수/추천수</th>
                            <th>책저자</th>
                            <th>출간일</th>
                        </tr>
                    </thead>
                    <tbody class="book-tbody">
                    {% for book in books %}
                        <tr>
                            <td><img src="{{ book.cover }}" class="list-img"></td>
                            <td><a href="{% url 'booker:detail' book.id %}" class="book-page">{{ book.title }}</a></td>
                            <td>{{ book.comment_set.count }}/{{ book.like.all.count }}</td>
                            <td>{{ book.rights }}</td>
                            <td>{{ book.issued_at }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="book-paginate">
                      {% for page_number in books.paginator.page_range %}
  {% if page_number >= books.number|add:-5 and page_number <= books.number|add:5 %}
    {% if page_number == books.number %}
        <li class="bookpg-li" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}"
                   href="#">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="bookpg-li">
            <a class="page-link" href="#" data-page="{{ page_number }}">
                {{ page_number }}
            </a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
                    <form id="searchForm" method="get" action="{{ request.path }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
            <input type="hidden" id="sa" name="sa" value="{{ sa }}">
        </form>
                </div>
            </div>
                <script>
                    $(document).ready(function(){
                           $("#cl1").on('click', function() {
                             var sa1Value = $("#sa1").val();
                             var baseUrl = window.location.href.split("?")[0];
                             var newUrl = baseUrl + "?sa=" + sa1Value;
                             window.location.href = newUrl;
                        });
                         $("#cl2").on('click', function() {
                             var sa2Value = $("#sa2").val();
                             var baseUrl = window.location.href.split("?")[0];
                             var newUrl = baseUrl + "?sa=" + sa2Value;
                             window.location.href = newUrl;
                        });
                        $(".page-link").on('click',function(){
                            const URLSearch = new URLSearchParams(location.search);
                            sa=  URLSearch.get('sa');
                            $("#sa").val(sa);
                            $("#page").val($(this).data("page"));
                            $("#searchForm").submit();
                        });
                    });
                </script>
            </div>
        </section>
{% endblock %}