booker/urls.py
from django.urls import path, include
from . import views

app_name='booker'

urlpatterns = [
    path('list', views.book_list, name='book-list'),
    path('detail/<int:book_id>/', views.book_detail, name='detail'),
    path('detail/like/<int:book_id>/', views.book_like, name='like'),
    path('detail/unlike/<int:book_id>/',views.book_unlike,name='unlike'),
    path('random/', views.book_reference, name='random'),
    path('profile/',views.book_profile, name='profile'),
    path('comment/delete/<int:comment_id>',views.comment_delete,name='comment-delete'),
    path('comment/update/<int:book_id>/<int:comment_id>', views.comment_update, name="comment-update"),
    path('about/us/',views.about_us,name="about-us")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from booker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('booker/',include('booker.urls')),
    path('', views.index,name='index'),
    path('common/',include('common.urls')),
    path('pybo/',include('pybo.urls'))
]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path
from . import views

app_name='pybo'

urlpatterns = [
    path('', views.index,name='index'),
    path('list/',views.ProfileViewList.as_view(),name='profile-list'),
    path('profile/create/',views.profile_create,name='profile-create'),
    path('profile/detail/<int:profile_id>',views.profile_detail,name='detail'),
    path('profile/like/<int:profile_id>',views.profile_like,name='like'),
    path('profile/unlike/<int:profile_id>',views.profile_unlike,name='unlike'),
    path('profile/comment/delete/<int:comment_id>',views.comment_delete,name='comment-delete'),
    path('profile/comment/update/<int:profile_id>/<int:comment_id>',views.comment_update,name='comment-update'),
    path('profile/profile/delete/<int:profile_id>',views.delete_profile,name='profile-delete'),
    path('profile/profile/update/<int:profile_id>',views.update_profile,name='profile-update'),
    path('hello/<int:user_id>',views.UserProfileView.as_view(),name='profile')


]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,
        initial-scale=1.0">
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <link rel="stylesheet" href="{% static 'css/style.css' %}?after">
        <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
         <title>booker</title>
    </head>
    <body>
        <header class="header">
            <a href="/" class="logo">Booker</a>
            <nav class="navbar">
                <a href="/">Home</a>
                <a href="{% url 'pybo:index' %}">Pybo</a>
                <a href="{% url 'booker:book-list' %}">List</a>
                <a href="{% url 'booker:random' %}">RandomBook</a>
                {% if user.is_authenticated %}
                <a href="{% url 'booker:profile' %}">{{ user.username }}</a>
                {% endif %}
                <a href="{% url 'booker:about-us' %}">AboutUs</a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </nav>
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/error.html
{% if form.errors %}
  {% for field in form %}
<div class="alert-danger">
  {% for error in field.errors %}
            <div class="alert-error">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
  {% endfor %}
    {% endfor %}
  {% for error in form.non_field_errors %}
            <div class="alert-error">
                <Strong>{{error}}</Strong>
            </div>
  {% endfor %}
            </div>
 {% endif %}

templates/pybo-base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,
        initial-scale=1.0">
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <link rel="stylesheet" href="{% static 'css/style.css' %}?after">
        <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
         <title>pybo</title>
    </head>
    <body>
        <header class="header">
            <a href="{% url 'pybo:index' %}" class="logo">Pybo</a>
            <nav class="navbar">
                <a href="{% url 'pybo:index' %}">Home</a>
                <a href="/">Booker</a>
                <a href="{% url 'pybo:profile-list' %}">Profiles</a>
                <a href="{% url 'pybo:profile-create' %}">NewProfile</a>
                {% if user.is_authenticated %}
                <a href="{% url 'pybo:profile' user.id %}">{{ user.username }}</a>
                {% endif %}
                <a href="{% url 'booker:about-us' %}">AboutUs</a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </nav>
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>